[project]
name = "hsr_unsupervised_models"
version = "0.1.0"
description = "Unsupervised models for HSR"
authors = [
  { name = "Marleen Streicher", email = "mstreicher@uni-potsdam.de" }
]
readme = "README.md"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["src"]
