name: env_hsr_adaptation
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.1.0=py310h06a4308_0
  - adwaita-icon-theme=47.0=unix_0
  - aiohappyeyeballs=2.4.4=py310h06a4308_0
  - aiohttp=3.11.10=py310h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - alsa-lib=1.2.13=hb9d3cd8_0
  - annotated-types=0.6.0=py310h06a4308_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - astunparse=1.6.3=py_0
  - async-timeout=5.0.1=py310h06a4308_0
  - at-spi2-atk=2.38.0=h0630a04_3
  - at-spi2-core=2.40.3=h0630a04_0
  - atk-1.0=2.38.0=h04ea711_2
  - attr=2.5.1=h166bdaf_1
  - attrs=24.3.0=py310h06a4308_0
  - blas=1.0=openblas
  - blinker=1.6.2=py310h06a4308_0
  - bottleneck=1.4.2=py310ha9d4c09_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py310h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.1.31=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.3.3=py310h06a4308_0
  - cairo=1.18.2=h3394656_1
  - certifi=2024.12.14=pyhd8ed1ab_0
  - cffi=1.17.1=py310h1fdaa30_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py310h06a4308_0
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.1=py310hdb19cb5_0
  - cryptography=43.0.3=py310h7825ff9_1
  - cvxopt=1.3.2=py310h1ac8b9e_3
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.27=h54b06d7_7
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.8.11=py310hf71b8c6_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - docker-pycreds=0.4.0=pyhd3eb1b0_0
  - dsdp=5.8=hf67d023_2
  - epoxy=1.5.10=h166bdaf_1
  - eval_type_backport=0.2.2=pyha770c72_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - expat=2.6.4=h6a678d5_0
  - fftw=3.3.10=nompi_hf1063bd_110
  - flatbuffers=23.5.26=h59595ed_1
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.51.0=py310h5eee18b_0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - frozenlist=1.5.0=py310h5eee18b_0
  - gdk-pixbuf=2.42.12=hb9ae30d_0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - giflib=5.2.2=h5eee18b_0
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.43=py310h06a4308_0
  - glib=2.82.2=h07242d1_1
  - glib-tools=2.82.2=h4833e2c_1
  - glpk=5.0=h445213a_0
  - gmp=6.3.0=hac33072_2
  - google-auth=2.29.0=py310h06a4308_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - graphite2=1.3.14=h295c915_1
  - graphviz=12.2.1=h5ae0cbf_1
  - grpcio=1.59.3=py310h1b8f574_0
  - gsl=2.7.1=h6e86dc7_1
  - gst-plugins-base=1.24.7=h0a52356_0
  - gstreamer=1.24.7=hf3bb09a_0
  - gtk3=3.24.43=h021d004_3
  - gts=0.7.6=h977cf35_4
  - h5py=3.12.1=nompi_py310hacc6608_103
  - harfbuzz=10.2.0=h4bba637_0
  - hdf5=1.14.4=nompi_h2d575fe_105
  - hicolor-icon-theme=0.17=ha770c72_2
  - icu=75.1=he02047a_0
  - idna=3.7=py310h06a4308_0
  - importlib-metadata=8.5.0=pyha770c72_1
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.31.0=pyh707e725_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.4.2=py310h06a4308_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - kiwisolver=1.4.4=py310h6a678d5_0
  - krb5=1.21.3=h143b758_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20230802.1=cxx17_h59595ed_0
  - libaec=1.1.3=h59595ed_0
  - libamd=3.3.3=ss783_h889e182
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libblas=3.9.0=26_linux64_openblas
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libbtf=2.3.2=ss783_h2377355
  - libcamd=3.3.3=ss783_h2377355
  - libcap=2.71=h39aace5_0
  - libcblas=3.9.0=26_linux64_openblas
  - libccolamd=3.3.4=ss783_h2377355
  - libcholmod=5.3.0=ss783_h3fa60b6
  - libclang-cpp15=15.0.7=default_h127d8a8_5
  - libclang-cpp19.1=19.1.7=default_hb5137d0_1
  - libclang13=19.1.7=default_h9c6a7e4_1
  - libcolamd=3.3.4=ss783_h2377355
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.11.1=h332b0f4_0
  - libcxsparse=4.4.1=ss783_h2377355
  - libdeflate=1.20=hd590300_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.4.3=h59595ed_0
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgcrypt-lib=1.11.0=hb9d3cd8_2
  - libgd=2.3.3=hd3e95f3_10
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.82.2=h2ff4ddf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.2.0=h77fa898_1
  - libgpg-error=1.51=hbd13f7d_1
  - libgrpc=1.59.3=hd6c4280_0
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.3=h5eee18b_0
  - libklu=2.3.5=ss783_hfbdfdfc
  - liblapack=3.9.0=26_linux64_openblas
  - libldl=3.3.2=ss783_h2377355
  - libllvm15=15.0.7=hb3ce162_4
  - libllvm19=19.1.7=ha7bfdaf_1
  - liblzma=5.6.4=hb9d3cd8_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=h27cfd23_1
  - libopenblas=0.3.28=pthreads_h94d23a6_1
  - libopus=1.3.1=h5eee18b_1
  - libparu=1.0.0=ss783_h8814b27
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.46=h943b412_0
  - libpq=17.2=h3b95a9b_1
  - libprotobuf=4.24.4=hf27288f_0
  - librbio=4.3.4=ss783_h2377355
  - libre2-11=2023.09.01=h7a70373_1
  - librsvg=2.58.4=h49af25d_2
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.20=h4ab18f5_0
  - libspex=3.2.1=ss783_h5a7e440
  - libspqr=4.3.4=ss783_hae1ff0d
  - libsqlite=3.48.0=hee588c1_1
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libsuitesparseconfig=7.8.3=ss783_h83006af
  - libsystemd0=256.9=h2774228_0
  - libtiff=4.6.0=h1dd3fc0_3
  - libumfpack=6.3.5=ss783_hd4f9ce1
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h7b6447c_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.8.0=hc4a0caf_0
  - libxml2=2.13.5=h8d12d68_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.9.4=h6a678d5_1
  - markdown=3.4.1=py310h06a4308_0
  - markupsafe=2.1.3=py310h5eee18b_0
  - matplotlib=3.9.2=py310h06a4308_1
  - matplotlib-base=3.9.2=py310hbfdbfaf_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - metis=5.1.0=hf484d3e_4
  - ml_dtypes=0.2.0=py310h1128e8f_0
  - mpfr=4.2.1=h90cbb55_3
  - mpg123=1.32.9=hc50e24c_0
  - mscorefonts=0.0.1=3
  - multidict=6.1.0=py310h5eee18b_0
  - mysql-common=9.0.1=h266115a_4
  - mysql-libs=9.0.1=he0572af_4
  - ncurses=6.5=he02047a_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nspr=4.36=h5888daf_0
  - nss=3.108=h159eef7_0
  - numexpr=2.10.1=py310hd28fd6d_0
  - numpy=1.26.4=py310heeff2f4_0
  - numpy-base=1.26.4=py310h8a23956_0
  - oauthlib=3.2.2=py310h06a4308_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openldap=2.6.9=he970967_0
  - openssl=3.4.0=h7b32b05_1
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=24.2=py310h06a4308_0
  - pandas=2.2.3=py310h6a678d5_0
  - pango=1.56.1=h861ebed_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.44=hba22ea6_2
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=10.4.0=py310he228d35_1
  - pip=24.2=py310h06a4308_0
  - pixman=0.44.2=h29eaf8c_0
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - ply=3.11=py310h06a4308_0
  - prompt-toolkit=3.0.48=pyha770c72_1
  - propcache=0.2.0=py310h5eee18b_0
  - psutil=6.1.1=py310ha75aee5_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pulseaudio-client=17.0=hb77b528_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.9.2=pyhd8ed1ab_0
  - pydantic-core=2.23.4=py310h505e2c1_0
  - pygments=2.18.0=pyhd8ed1ab_1
  - pyjwt=2.9.0=py310h06a4308_0
  - pyopenssl=24.2.1=py310h06a4308_0
  - pyparsing=3.2.0=py310h06a4308_0
  - pyqt=5.15.10=py310h6a678d5_0
  - pyqt5-sip=12.13.0=py310h5eee18b_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.14=hd12c33a_0_cpython
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-dotenv=0.21.0=py310h06a4308_0
  - python-flatbuffers=24.3.25=py310h06a4308_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytz=2024.1=py310h06a4308_0
  - pyyaml=6.0.2=py310h5eee18b_0
  - pyzmq=26.2.0=py310h71f11fc_3
  - qt-main=5.15.15=hc3cb62f_2
  - re2=2023.09.01=h7f4b329_1
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py310h06a4308_1
  - requests-oauthlib=2.0.0=py310h06a4308_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scikit-learn=1.5.2=py310h6a678d5_0
  - scipy=1.13.1=py310heeff2f4_1
  - seaborn=0.13.2=py310h06a4308_0
  - sentry-sdk=2.18.0=py310h06a4308_0
  - setproctitle=1.2.2=py310h5eee18b_2
  - setuptools=75.1.0=py310h06a4308_0
  - sip=6.7.12=py310h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - smmap=4.0.0=pyhd3eb1b0_0
  - snappy=1.1.10=h6a678d5_1
  - sqlite=3.48.0=h9eae976_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - suitesparse=7.8.3=ss783_h36e971b
  - termcolor=2.1.0=py310h06a4308_0
  - threadpoolctl=3.5.0=py310h2f386ee_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.0.1=py310h06a4308_0
  - tornado=6.4.2=py310h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing=3.10.0.0=py310h06a4308_0
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=15.1.0=py310h5eee18b_0
  - urllib3=2.2.3=py310h06a4308_0
  - wandb=0.19.2=py310h69e60fc_0
  - wayland=1.23.1=h3e06ad9_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - werkzeug=3.0.6=py310h06a4308_0
  - wheel=0.44.0=py310h06a4308_0
  - wrapt=1.14.1=py310h5eee18b_0
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.42=h4ab18f5_0
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.5=he73a12e_0
  - xorg-libx11=1.8.11=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxinerama=1.1.5=h5888daf_1
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xf86vidmodeproto=2.3.1=hb9d3cd8_1005
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.18.0=py310h5eee18b_0
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - adapt==0.4.3
      - aggdraw==1.3.19
      - argparse==1.4.0
      - docstring-parser==0.17.0
      - filelock==3.16.1
      - fsspec==2024.12.0
      - gast==0.4.0
      - google-auth-oauthlib==0.4.6
      - hsr-unsupervised-models==0.1.0
      - jinja2==3.1.5
      - keras==2.11.0
      - libclang==18.1.1
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - mpmath==1.3.0
      - namex==0.0.8
      - networkx==3.4.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - optree==0.13.1
      - protobuf==3.19.6
      - pydot==3.0.4
      - python-graphviz==0.20.3
      - rich==13.9.4
      - scikeras==0.13.0
      - shtab==1.7.2
      - sympy==1.13.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.18.0
      - tensorflow-estimator==2.11.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - triton==3.1.0
      - typeguard==4.4.4
      - typing-extensions==4.15.0
      - tyro==0.9.32
      - visualkeras==0.1.4
prefix: /home/user/.conda/envs/env_hsr_adaptation
